name: "Sync logoURIs"
on:
  workflow_dispatch
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  sync-logoURIs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
        pnpm-version: [8.9.2]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies & sync logoURIs
        env: 
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
        run: pnpm install && pnpm run syncLogoURIs
        working-directory: "./lists/token-lists/default-token-list"
